# Generated by Django 5.0.4 on 2024-04-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
